"""zxc

Revision ID: ace57fcb9cbb
Revises: 
Create Date: 2026-03-13 11:59:54.865344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace57fcb9cbb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reference_tariffs', sa.Column('organization_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_reference_tariffs_organization_id'), 'reference_tariffs', ['organization_id'], unique=False)
    op.create_foreign_key(None, 'reference_tariffs', 'organizations', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reference_tariffs', type_='foreignkey')
    op.drop_index(op.f('ix_reference_tariffs_organization_id'), table_name='reference_tariffs')
    op.drop_column('reference_tariffs', 'organization_id')
    # ### end Alembic commands ###
